version: '3'

services:
  nginx:
    restart: always
    image: mitwilsch/host-router:latest
    container_name: prod_nginx
    volumes:
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./repos:/App/repos/
    ports:
      - 80:80
      - 443:443

  statMonitor:
    image: mitwilsch/stat-monitor:latest
    container_name: statMonitor
    ports:
      - '80'
      - '8080'
