version: '3'

services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    volumes:
      - ./nginx/${NGINX_CONF}:/etc/nginx/nginx.conf

      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
      - '../mitchell.schooler.me/dist:/var/www/mitchell.schooler.me'
      - '../schooler.me/dist:/var/www/schooler.me'
      - '../toto/dist:/var/www/toto'
      - '../stat-monitor/dist:/var/www/stat-monitor'
    ports:
      - 80:80
      - 443:443

  statMonitor:
    image: mitwilsch/stat-monitor:latest
    container_name: statMonitor
    ports:
      - '8080'
