version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: prod_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  mitchell:
    image: mitwilsch/mitchell.schooler.me:latest
    container_name: mitchell
    expose:
      - '80'

  schooler:
    image: mitwilsch/schooler.me:latest
    container_name: schooler
    expose:
      - '80'

  statMonitor:
    image: mitwilsch/stat-monitor:latest
    container_name: statMonitor
    ports:
      - '80'
      - '8080'

        #toto:
        #image: mitwilsch/toto:latest
        #container_name: toto
        #expose:
        #- '80'
