version: '3'

services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    volumes:
      - ./nginx/${NGINX_CONF}:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
      - '../mitchell.schooler.me/dist:/var/www/mitchell.schooler.me'
      - '../schooler.me/dist:/var/www/schooler.me'
      - '../toto/dist:/var/www/toto'
    ports:
      - 80:80
      - 443:443

  statMonitor:
    image: mitwilsch/stat-monitor:latest
    container_name: statMonitor
    ports:
      - '80'
      - '8080'
